### ISSUE TITLE
Instrument Tracks Toggle

### ISSUE THREAD

**Issue by x7xixi** [ArijanJ/midi-converter#19]
You can only toggle the instrument tracks during import, wondering if it'd be possible to do that in editor too?

**Comment by ArijanJ** [comment]
That's not really possible without some major changes, but we could maybe have a sheet preview window during the import stage if it works? (it would change if you disable a track)

**Comment by x7xixi** [comment]
AAAh RIP, sometimes its hard to find the right track to disable especially with midi files that have tons of instrument tracks that are unnamed. I see the preview feature being useful but if possible having the implementation of tranposition changes too during preview.

Also idk if this might ease things but you could have a save state of some sort that saves only the transpositions and whatnot changed in the editor and have it refresh and re-render the entire thing but with only the selected instrument tracks possibly? Basically just moving the instrument track toggle thing to the editor instead of having it only for the import stage

**Comment by ArijanJ** [comment]
So it wasn't as hard to implement as I thought, should be available now, please try it and let me know what you think :)

**Comment by x7xixi** [comment]
Very nice, works as expected. Thanks! Gonna make sheet conversions so much easier 👍
